export const SET_CUSTOMER_ACCESS_TOKEN = 'SET_CUSTOMER_ACCESS_TOKEN';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';
export const SET_VENDORS_INFORMATION_SUCCESS = 'SET_VENDORS_INFORMATION_SUCCESS'
export const SET_VENDORS_INFORMATION_FAILED = 'SET_VENDORS_INFORMATION_FAILED'
